//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNghePhanMen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSDLBanThuoc : DbContext
    {
        public CSDLBanThuoc()
            : base("name=CSDLBanThuoc")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<brand> brands { get; set; }
        public DbSet<cart_items> cart_items { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<coupon_conditions> coupon_conditions { get; set; }
        public DbSet<coupon> coupons { get; set; }
        public DbSet<district> districts { get; set; }
        public DbSet<order_items> order_items { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<post_categories> post_categories { get; set; }
        public DbSet<post_tags> post_tags { get; set; }
        public DbSet<post> posts { get; set; }
        public DbSet<product_images> product_images { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<province> provinces { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tag> tags { get; set; }
        public DbSet<user_roles> user_roles { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<ward> wards { get; set; }
    }
}
