//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongNghePhanMen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;

    public partial class user
    {
        public user()
        {
            this.carts = new HashSet<cart>();
            this.orders = new HashSet<order>();
            this.posts = new HashSet<post>();
            this.user_roles = new HashSet<user_roles>();
        }
    
        public int id { get; set; }

        //[Required(ErrorMessage = "Không được bỏ trống tên")]
        //[Display(Name = "Tên tài khoản")]
        public string full_name { get; set; }

        //[Display(Name = "Số điện thoại")]
        //[Required(ErrorMessage = "Không được bỏ trống số điện thoại")]
        //[Phone]
        public string phone_number { get; set; }

        //[Display(Name = "Email")]
        //[Required(ErrorMessage = "Không được bỏ trống email")]
        //[EmailAddress]
        public string email { get; set; }

        //[Required(ErrorMessage = "Không được bỏ trống password")]
        //[StringLength(20, MinimumLength = 6, ErrorMessage = "Chiều dài tối thiểu 6 kí tự")]
        //[Display(Name = "Mật khẩu")]
        public string password { get; set; }
        public string avatar { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual ICollection<cart> carts { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<user_roles> user_roles { get; set; }
    }
}
